application:
 security:
  jwt:
   secret-key: ${JWT_SECRET_KEY}
   expiration: 15 # This is minutes
  cookie:
   name: ${COOKIE_NAME}
   name-refresh: ${COOKIE_REFRESH_NAME}
   http-only: true
   secure: true # true is only for https, this will be modified
   max-age: 15m
   max-age-refresh: 7d
   same-site: Strict